import esbuild from "esbuild";
import process from "process";
const path = require("node:path");
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const wasmPlugin = {
    name: "wasm",

    setup(build) {
        build.onResolve({ filter: /\.wasm$/ }, (args) => {
		console.log(args);
		return {
            // FIXME: hack
            path: path.join("node_modules", args.path),
            namespace: "wasm-binary",
        };
	
		});

        build.onLoad({ filter: /.*/, namespace: "wasm-binary" }, async (args) => ({
            contents: await fs.promises.readFile(args.path),
            loader: "binary",
        }));
    },
};

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	plugins: [
		wasmPlugin
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});





if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
